<?php

// Disables the generation of the menu completely
// define('CIVICRM_DISABLE_DEFAULT_MENU', TRUE);

/**
 * Implementation of hook_block_info
 */
function civicrm_navblock_block_info() {
  $blocks['civicrm_navblock'] = array(
    'info' => t('CiviCRM Menu'),
    'status' => TRUE,
    'region' => 'content',
    'cache' => BLOCK_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view
 */
function civicrm_navblock_block_view($delta = '') {
  switch ($delta) {
    case 'civicrm_navblock':
      civicrm_initialize();

      // Add CiviCRM's basic JS & CSS, cj() is required for the menu.
      CRM_Core_Resources::singleton()->addCoreResources();

      $smarty = CRM_Core_Smarty::singleton();
      require_once 'CRM/Core/Smarty/plugins/function.crmNavigationMenu.php';

      $block = array(
        'subject' => '',
        'content' => smarty_function_crmNavigationMenu(array(), $smarty),
      );
      return $block;
      break;
    default:
  }
}
