<?php

// Disables the generation of the menu completely
// define('CIVICRM_DISABLE_DEFAULT_MENU', TRUE);

/**
 * Implementation of hook_block_info
 */
function civicrm_navblock_block_info() {
  $blocks['civicrm_navblock'] = array(
    'info' => t('CiviCRM Menu'),
    'status' => TRUE,
    'region' => 'content',
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view
 */
function civicrm_navblock_block_view($delta = '') {
  switch ($delta) {
    case 'civicrm_navblock':
      civicrm_initialize();

      // Add CiviCRM's basic JS & CSS, cj() is required for the menu.
      CRM_Core_Resources::singleton()->addCoreResources();

      $session = CRM_Core_Session::singleton();
      $contactID = $session->get('userID');

      if ($contactID) {
        $navigation = CRM_Core_BAO_Navigation::createNavigation($contactID);
        $smarty = CRM_Core_Smarty::singleton();
        $smarty->assign('navigation', $navigation);
        $content = $smarty->fetch('CRM/common/drupal.tpl');
        // templates/CRM/common/drupal.tpl
        // CRM/common/Navigation.tpl
      }

      // Render page header
      if ($region = CRM_Core_Region::instance('html-header', FALSE)) {
        CRM_Utils_System::addHTMLHead($region->render(''));
      }

      $block = array(
        'subject' => '',
        'content' => $content,
      );

      return $block;
      break;
    default:
  }
}
